### ISSUE TITLE
Debian .deb (apt) install

### ISSUE THREAD

**Issue by justinmichaelvieira** [thoughtbot/complexity#11]
Hi there - I am interested in using this with Elixir and Python code for my work. Since I primarily use Ubuntu, I'd like to try doing a a debian .deb build script.

I see that currently there is only the Mac Homebrew install - what exactly does the homebrew install do? I can likely replicate what it's doing for Debian/Ubuntu linux platforms, if someone can point me to the Homebrew install scripts, or just let me know what the Homebrew install does.

Thanks!

**Comment by joshuaclayton** [comment]
Hi @justinmichaelvieira thanks for your interest!

While I haven't worked with Homebrew directly ([formula here](https://github.com/thoughtbot/homebrew-formulae/blob/master/Formula/complexity.rb)), I understand it to download the repo, verify the checksum, run the system command (in this case, it uses Rust's cargo package manager), and then run tests to verify behavior.
