### ISSUE TITLE
Installing from Homebrew on M1 mac

### ISSUE THREAD

**Issue by brian-penguin** [thoughtbot/complexity#13]
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/7143499/156444152-f1cf11b7-857e-4a9d-a4b9-61c7ba677a23.png">

```
==> Downloading https://github.com/thoughtbot/complexity/archive/0.3.0.tar.gz
Already downloaded: /Users/briantenggren/Library/Caches/Homebrew/downloads/ccb5fd1da73aa8733102237a645c4bdebb8ac258d9fbd417a20f694f0a2a3505--complexity-0.3.0.tar.gz
==> Installing complexity from thoughtbot/formulae
[34m==>[0m [1mcargo install[0m
Last 15 lines from /Users/briantenggren/Library/Logs/Homebrew/complexity/01.cargo:
     |
1254 |     let div = n / bits;
     |                 ^ no implementation for `usize / u32`
     |
     = help: the trait `Div<u32>` is not implemented for `usize`

   Compiling dirs-next v2.0.0
Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `lexical-core` due to 27 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `complexity v0.3.0 (/private/tmp/complexity-20220302-14250-1nwsd5q/complexity-0.3.0)`, intermediate artifacts can be found at `/private/tmp/complexity-20220302-14250-1nwsd5q/complexity-0.3.0/target`

Caused by:
  build failed

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/thoughtbot/homebrew-formulae/issues

These open issues may also help:
Release complexity 0.4.1 https://github.com/thoughtbot/homebrew-formulae/pull/71
```

When running 
```sh
brew tap thoughtbot/formulae
brew install complexity
```

**Comment by joshuaclayton** [comment]
@brimatteng can you update the thoughtbot formulae and try again? I just pushed https://github.com/thoughtbot/homebrew-formulae/commit/6a62cb2cb7aa123bef603937da0166e665b7882d, which should get to the latest stable version and get past the issues with lexical-core that were resolved in https://github.com/thoughtbot/complexity/commit/50aac0bb94948c61bc0fcda53441a8b9b1ed76ac.

**Comment by brian-penguin** [comment]
Successfully installed! Unable to run though
<img width="720" alt="image" src="https://user-images.githubusercontent.com/7143499/156594959-d59a44fe-8b96-41e9-83b9-85d2a1072906.png">

**Comment by joshuaclayton** [comment]
@brimatteng yeah, that exception you're seeing isn't super helpful – I'm sorry about that.

Any chance you have a working Rust environment set up locally? I have a hunch that it's related to [MiMalloc](https://docs.rs/mimalloc/latest/mimalloc/) (it speeds up execution by ~22% on my machine over the default Rust allocator, which isn't nothing!) If you do, I'm happy to push a branch up for you to build locally and verify MiMalloc is the culprit.

**Comment by joshuaclayton** [comment]
@brimatteng as a reference, here's the corresponding change in another tool I'd built https://github.com/unused-code/unused/pull/37 and the corresponding Homebrew formula change: https://github.com/unused-code/homebrew-formulae/commit/c8abd145963af5347d4c2bde698766ee75c8bec2

**Comment by brian-penguin** [comment]
Ive maybe got some time tomorrow i can take a crack at it. It's hard to debug the brew version so building it locally might do better
