### ISSUE TITLE
Linux releases

### ISSUE THREAD

**Issue by pylipp** [thoughtbot/complexity#5]
From the [github actions config](https://github.com/thoughtbot/complexity/blob/main/.github/workflows/release.yml#L71) it appears that Linux builds should happen, and be deployed to the releases page, yet I can only find darwin releases there.

**Comment by joshuaclayton** [comment]
@pylipp you're right, it's been configured, but right now the build is broken. I don't use Linux; anything stand out to you in the failure that might be worth exploring? Here's the failure for the 0.2 release: https://github.com/thoughtbot/complexity/runs/1538503734?check_suite_focus=true

**Comment by joshuaclayton** [comment]
@pylipp huzzah, it looks like this has been resolved recently: https://github.com/BurntSushi/ripgrep/pull/1728/commits/aae22d7f205ab079aed005878b757d6eaa893e2b I just checked [the most recent release](https://github.com/BurntSushi/ripgrep/releases/tag/12.1.1) on ripgrep and saw a musl release, so I'm guessing this will resolve it.

I'm going to be cutting a 0.3 release soon – I'll tag with an alpha tag to verify first.

**Comment by joshuaclayton** [comment]
@pylipp Ignore the version number – want to give this one a whirl? I had to bump tags after my first attempt didn't work. Seems mimalloc was causing an issue, which I've removed. https://github.com/thoughtbot/complexity/releases/tag/0.3.1.alpha

**Comment by joshuaclayton** [comment]
@pylipp Ignore the last version – I've cut 0.3.0 and things are working now! You can grab the latest release here: https://github.com/thoughtbot/complexity/releases/tag/0.3.0

**Comment by pylipp** [comment]
Works like a charm, thanks for the quick fix!
