### ISSUE TITLE
Explanation of values

### ISSUE THREAD

**Issue by pylipp** [thoughtbot/complexity#9]
Hej, I've been experimenting with the tool.

I was wondering about the meaning of the computed complexity values. Obviously I'm too lazy to read the referenced paper, I totally understand if you direct me to that :D. Still a small TLDR would be nice:
How can I categorize the values (e.g. what's the threshold marking 'critical' complexity)?
Are the values independent of the file size? Are larger files assigned a larger complexity automatically?

**Comment by joshuaclayton** [comment]
@pylipp that's a great question and one that I don't quite know the answer to yet. The algorithm we use is one very quickly hacked together that correlated with what we were seeing generally from [rubycritic](https://github.com/whitesmith/rubycritic) from one of our moderately large internal Rails codebases (~100kloc).

When I run the tool, I'm doing a numeric sort `complexity | sort -n --reverse | head -n 20` to get a sense of where to focus within new codebases. There might be too strong a correlation with file length – and the algorithm can be adjusted if that's the case.

If the score of a file is < 100, it's *likely* it's going to be easy to grok. Again, this is an approximation tool, and not one that interprets files. I don't expect that to change anytime soon.

I did break apart scoring to use the visitor pattern as a way to encourage other algorithms/approaches be used. I would imagine this could be configurable on a per-file-type basis eventually, or score differently for files that don't "roll back up" like Haskell or Elm versus Ruby or Elixir.

The current algorithm: https://github.com/thoughtbot/complexity/commit/7fb66a283a1bfc975d6be5dcad307268560c2a97#diff-0e83e34ba12421d41f8a2e93ca67eff995ef8511c656b50a56e45fc9167d8abe

The current scoring structure that uses the scoring visitor: https://github.com/thoughtbot/complexity/blob/4112cda9cbc476205484b6424dc9b3d6c3d80f18/src/scoring.rs#L14-L40

The current written-out way to read the current scoring algorithm: https://github.com/thoughtbot/complexity/commit/7fb66a283a1bfc975d6be5dcad307268560c2a97#diff-12b7e19d8f3e5e1cf0dbe75aff102362944bb1cf00c4634b2aec22fe393c16e9R115-R133
